In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
st= pd.read_csv("D:\Artifical Intelligent\Dataset\student\student-mat.csv")

In [3]:
print(st.head)

<bound method NDFrame.head of     school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0    GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...                                                                                                                                                                                 
1    GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...                                                                                                                                                                                 
2    GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...                                                                                                                                                                                 
3    GP;"F";15;"U";"GT3";"T";4;2;"health";

In [4]:
st= pd.read_csv("D:\Artifical Intelligent\Dataset\student\student-mat.csv",sep =';')
print(st.head)

<bound method NDFrame.head of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freet

In [5]:
st=st[["school","studytime","failures","absences","G1","G2","G3"]]
st.head


<bound method NDFrame.head of     school  studytime  failures  absences  G1  G2  G3
0       GP          2         0         6   5   6   6
1       GP          2         0         4   5   5   6
2       GP          2         3        10   7   8  10
3       GP          3         0         2  15  14  15
4       GP          2         0         4   6  10  10
..     ...        ...       ...       ...  ..  ..  ..
390     MS          2         2        11   9   9   9
391     MS          1         0         3  14  16  16
392     MS          1         3         3  10   8   7
393     MS          1         0         0  11  12  10
394     MS          1         0         5   8   9   9

[395 rows x 7 columns]>

In [6]:
print(st.head)

<bound method NDFrame.head of     school  studytime  failures  absences  G1  G2  G3
0       GP          2         0         6   5   6   6
1       GP          2         0         4   5   5   6
2       GP          2         3        10   7   8  10
3       GP          3         0         2  15  14  15
4       GP          2         0         4   6  10  10
..     ...        ...       ...       ...  ..  ..  ..
390     MS          2         2        11   9   9   9
391     MS          1         0         3  14  16  16
392     MS          1         3         3  10   8   7
393     MS          1         0         0  11  12  10
394     MS          1         0         5   8   9   9

[395 rows x 7 columns]>


In [7]:
st=st[["school","studytime","failures","absences","G1","G2","G3"]]
st.shape


(395, 7)

In [8]:
st=st[["studytime","failures","absences","G1","G2","G3"]]
st.shape

(395, 6)

In [9]:
feat=st[0:5]
feat.head

<bound method NDFrame.head of    studytime  failures  absences  G1  G2  G3
0          2         0         6   5   6   6
1          2         0         4   5   5   6
2          2         3        10   7   8  10
3          3         0         2  15  14  15
4          2         0         4   6  10  10>

In [10]:
feat=st[0:4]
st.head

<bound method NDFrame.head of      studytime  failures  absences  G1  G2  G3
0            2         0         6   5   6   6
1            2         0         4   5   5   6
2            2         3        10   7   8  10
3            3         0         2  15  14  15
4            2         0         4   6  10  10
..         ...       ...       ...  ..  ..  ..
390          2         2        11   9   9   9
391          1         0         3  14  16  16
392          1         3         3  10   8   7
393          1         0         0  11  12  10
394          1         0         5   8   9   9

[395 rows x 6 columns]>

In [11]:
feat.shape


(4, 6)

In [12]:
st.shape

(395, 6)

In [13]:
data=np.array([st])

In [14]:
feat=data[:0,-1]
feat.shape

(0, 6)

In [15]:
print(data)

[[[ 2  0  6  5  6  6]
  [ 2  0  4  5  5  6]
  [ 2  3 10  7  8 10]
  ...
  [ 1  3  3 10  8  7]
  [ 1  0  0 11 12 10]
  [ 1  0  5  8  9  9]]]


In [16]:
print(feat)

[]


In [17]:
feat=data[:,0:-1]

In [18]:
print(feat)

[[[ 2  0  6  5  6  6]
  [ 2  0  4  5  5  6]
  [ 2  3 10  7  8 10]
  ...
  [ 1  0  3 14 16 16]
  [ 1  3  3 10  8  7]
  [ 1  0  0 11 12 10]]]


In [19]:
feat=data[:,0:4]
print(feat)

[[[ 2  0  6  5  6  6]
  [ 2  0  4  5  5  6]
  [ 2  3 10  7  8 10]
  [ 3  0  2 15 14 15]]]


In [20]:
feat=data[:,0,-1]
print(feat)

[6]


In [21]:
st.head


<bound method NDFrame.head of      studytime  failures  absences  G1  G2  G3
0            2         0         6   5   6   6
1            2         0         4   5   5   6
2            2         3        10   7   8  10
3            3         0         2  15  14  15
4            2         0         4   6  10  10
..         ...       ...       ...  ..  ..  ..
390          2         2        11   9   9   9
391          1         0         3  14  16  16
392          1         3         3  10   8   7
393          1         0         0  11  12  10
394          1         0         5   8   9   9

[395 rows x 6 columns]>

In [22]:
feat=st[["studytime","failures","absences","G1","G2"]]
feat.head

<bound method NDFrame.head of      studytime  failures  absences  G1  G2
0            2         0         6   5   6
1            2         0         4   5   5
2            2         3        10   7   8
3            3         0         2  15  14
4            2         0         4   6  10
..         ...       ...       ...  ..  ..
390          2         2        11   9   9
391          1         0         3  14  16
392          1         3         3  10   8
393          1         0         0  11  12
394          1         0         5   8   9

[395 rows x 5 columns]>

In [23]:
tar=st[["G3"]]
tar.head

<bound method NDFrame.head of      G3
0     6
1     6
2    10
3    15
4    10
..   ..
390   9
391  16
392   7
393  10
394   9

[395 rows x 1 columns]>

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
rd=LinearRegression()


In [27]:
x_train,x_test,y_train,y_test = train_test_split(feat,tar,test_size=0.2)

In [28]:
rd.fit(x_train,y_train)

LinearRegression()

In [29]:
accLinearRegression=rd.score(x_test,y_test)
print(accLinearRegression)

0.7958516440582319


In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn=KNeighborsClassifier()

In [32]:
knn.fit(x_test,y_test)

<ipython-input-32-c3be45e0a559>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_test,y_test)


KNeighborsClassifier()

In [33]:
knn.fit(x_train,y_train)

<ipython-input-33-17b0ab828d68>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train,y_train)


KNeighborsClassifier()

In [34]:
x_train,x_test,y_train,y_test = train_test_split(feat,tar,test_size=0.2)

In [35]:
knn.fit(x_train,y_train)

<ipython-input-35-17b0ab828d68>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(x_train,y_train)


KNeighborsClassifier()

In [36]:
acc_knn =knn.score(x_test,y_test)

In [37]:
print(acc_knn)

0.3924050632911392


In [38]:
from sklearn import svm


In [39]:
svm.fit(x_train,y_train)

AttributeError: module 'sklearn.svm' has no attribute 'fit'

In [ ]:
s=svm()

In [ ]:
model=svm.SVC(kernel='linear')

model.fit(x_train,y_train)

In [ ]:
acc=model.score(x_test,y_test)

In [ ]:
from sklearn.svm import SVC

In [ ]:
ss=SVC()

In [ ]:
ss.fit(x_train, y_train)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(feat,tar,test_size=0.2)

In [ ]:
acc=ss.score(x_test,y_test)

In [ ]:
print(acc)

In [ ]:
print(accLinearRegression)
print(acc_knn)
print(acc)

In [ ]:
pre=rd.predict(x_test)

In [43]:
st.head

<bound method NDFrame.head of      studytime  failures  absences  G1  G2  G3
0            2         0         6   5   6   6
1            2         0         4   5   5   6
2            2         3        10   7   8  10
3            3         0         2  15  14  15
4            2         0         4   6  10  10
..         ...       ...       ...  ..  ..  ..
390          2         2        11   9   9   9
391          1         0         3  14  16  16
392          1         3         3  10   8   7
393          1         0         0  11  12  10
394          1         0         5   8   9   9

[395 rows x 6 columns]>

In [48]:
g=np.array([[1,0,3,14,16]])

In [49]:
knn.predict(g)

array([15], dtype=int64)